name: multiplatform_key_value_store_web
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: ironman <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  multiplatform_key_value_store:
    path: ../multiplatform_key_value_store

dev_dependencies:
  build_runner: ^0.9.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.1
  test: ^1.0.0
  mockito: ^3.0.0
